//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangResource {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly is encrypted {0} 的本地化字符串。
        /// </summary>
        public static string CM_AssemblyEncrypted {
            get {
                return ResourceManager.GetString("CM_AssemblyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class count: {0} 的本地化字符串。
        /// </summary>
        public static string CM_ClassCount {
            get {
                return ResourceManager.GetString("CM_ClassCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found {0}. 的本地化字符串。
        /// </summary>
        public static string CM_FileNotFonud {
            get {
                return ResourceManager.GetString("CM_FileNotFonud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [FMOD Error]  的本地化字符串。
        /// </summary>
        public static string CM_FMODErr {
            get {
                return ResourceManager.GetString("CM_FMODErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] Section {1} have duplicated keywords {2}. Duplicated keywords will be ignored except the last one with non-empty value(s). 的本地化字符串。
        /// </summary>
        public static string CM_IniKeywordRep {
            get {
                return ResourceManager.GetString("CM_IniKeywordRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ini section {0} is inherited from a missing section {1}. 的本地化字符串。
        /// </summary>
        public static string CM_IniParentMissing {
            get {
                return ResourceManager.GetString("CM_IniParentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] There are sections with a same name {1}. An error occured when trying to merge them. Error: {2}. 的本地化字符串。
        /// </summary>
        public static string CM_IniSegmentConcatErr {
            get {
                return ResourceManager.GetString("CM_IniSegmentConcatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] There are sections with a same name {1}. Duplicated keywords {2} found then trying to merge the sections. Those keyword will be ignored. 的本地化字符串。
        /// </summary>
        public static string CM_IniSegmentConcatKeyRep {
            get {
                return ResourceManager.GetString("CM_IniSegmentConcatKeyRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] There are sections with a same name {1}. They will be merged into one section. 的本地化字符串。
        /// </summary>
        public static string CM_IniSegmentRep {
            get {
                return ResourceManager.GetString("CM_IniSegmentRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The screen resolution setting in ra2{0}.ini is invalid. Restored to 800x600. 的本地化字符串。
        /// </summary>
        public static string CM_InvaildResol {
            get {
                return ResourceManager.GetString("CM_InvaildResol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method count: {0} 的本地化字符串。
        /// </summary>
        public static string CM_MethodCount {
            get {
                return ResourceManager.GetString("CM_MethodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find tile texture {0}. 的本地化字符串。
        /// </summary>
        public static string CM_MissingTileImage {
            get {
                return ResourceManager.GetString("CM_MissingTileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} is not a instance(ScriptProc) 的本地化字符串。
        /// </summary>
        public static string CM_ObjNotInit {
            get {
                return ResourceManager.GetString("CM_ObjNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script assembly loaded {0} 的本地化字符串。
        /// </summary>
        public static string CM_ScriptAssemblyLoaded {
            get {
                return ResourceManager.GetString("CM_ScriptAssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script assembly not found {0} 的本地化字符串。
        /// </summary>
        public static string CM_ScriptAssemblyNotFound {
            get {
                return ResourceManager.GetString("CM_ScriptAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script have been loaded for object {0}. 的本地化字符串。
        /// </summary>
        public static string CM_ScriptLoaded {
            get {
                return ResourceManager.GetString("CM_ScriptLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} &apos;s script is not loaded. Probably due to the non-existance of its corresponding static class. 的本地化字符串。
        /// </summary>
        public static string CM_ScriptNotLoaded {
            get {
                return ResourceManager.GetString("CM_ScriptNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} &apos;s script is not loaded. Because the object doesn&apos;t have a script name. 的本地化字符串。
        /// </summary>
        public static string CM_ScriptNotUsed {
            get {
                return ResourceManager.GetString("CM_ScriptNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find sound {0} 的本地化字符串。
        /// </summary>
        public static string CM_SoundNotFound {
            get {
                return ResourceManager.GetString("CM_SoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find tile file {0} 的本地化字符串。
        /// </summary>
        public static string CM_TileFileMissing {
            get {
                return ResourceManager.GetString("CM_TileFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game timer started: {0} 的本地化字符串。
        /// </summary>
        public static string CM_TimerStarted {
            get {
                return ResourceManager.GetString("CM_TimerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type count{0} 的本地化字符串。
        /// </summary>
        public static string CM_TypeCount {
            get {
                return ResourceManager.GetString("CM_TypeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use default settings. 的本地化字符串。
        /// </summary>
        public static string CM_UseDefaultSet {
            get {
                return ResourceManager.GetString("CM_UseDefaultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console 的本地化字符串。
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Console_Submit {
            get {
                return ResourceManager.GetString("Console_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File {0} has a invalid format. 的本地化字符串。
        /// </summary>
        public static string Ex_InvaildFileFormat {
            get {
                return ResourceManager.GetString("Ex_InvaildFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} have already loaded. 的本地化字符串。
        /// </summary>
        public static string Ex_ObjectAlreadyLoaded {
            get {
                return ResourceManager.GetString("Ex_ObjectAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} is not initialized. 的本地化字符串。
        /// </summary>
        public static string Ex_ObjectNotInit {
            get {
                return ResourceManager.GetString("Ex_ObjectNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Error 的本地化字符串。
        /// </summary>
        public static string Ex_ScriptError {
            get {
                return ResourceManager.GetString("Ex_ScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The script function&apos;s argument doesn&apos;t match the corresponding event&apos;s. The arugment of {0} should be {1}. 的本地化字符串。
        /// </summary>
        public static string Ex_ScriptSignMismatch {
            get {
                return ResourceManager.GetString("Ex_ScriptSignMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Console {
            get {
                return ResourceManager.GetString("ExPrint_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Data:  的本地化字符串。
        /// </summary>
        public static string ExPrint_ExtraData {
            get {
                return ResourceManager.GetString("ExPrint_ExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Variables:  的本地化字符串。
        /// </summary>
        public static string ExPrint_LocalVars {
            get {
                return ResourceManager.GetString("ExPrint_LocalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Method {
            get {
                return ResourceManager.GetString("ExPrint_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Error:  的本地化字符串。
        /// </summary>
        public static string ExPrint_ScriptError {
            get {
                return ResourceManager.GetString("ExPrint_ScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Source {
            get {
                return ResourceManager.GetString("ExPrint_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thread:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Thread {
            get {
                return ResourceManager.GetString("ExPrint_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Time {
            get {
                return ResourceManager.GetString("ExPrint_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version:  的本地化字符串。
        /// </summary>
        public static string ExPrint_Version {
            get {
                return ResourceManager.GetString("ExPrint_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention:  的本地化字符串。
        /// </summary>
        public static string MsgLvl_Attention {
            get {
                return ResourceManager.GetString("MsgLvl_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERROR:  的本地化字符串。
        /// </summary>
        public static string MsgLvl_Error {
            get {
                return ResourceManager.GetString("MsgLvl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MsgLvl_Information {
            get {
                return ResourceManager.GetString("MsgLvl_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MsgLvl_Normal {
            get {
                return ResourceManager.GetString("MsgLvl_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING:  的本地化字符串。
        /// </summary>
        public static string MsgLvl_Warning {
            get {
                return ResourceManager.GetString("MsgLvl_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [MISSING] 的本地化字符串。
        /// </summary>
        public static string StrTable_Missing {
            get {
                return ResourceManager.GetString("StrTable_Missing", resourceCulture);
            }
        }
    }
}
